# Change these first
owner: diveliastudio # Your GitHub organization or username, where this repository lives
repo: cobi-upptime # The name of this repository

sites:
  - name: Cobi API
    url: $API_COBI
  
  - name: MQTT Port
    check: "tcp-ping"
    url: $COBI_MQTT
    port: 1883

  - name: WS Port
    check: "tcp-ping"
    url: $COBI_MQTT
    port: 8083

status-website:
  # Add your custom domain name, or remove the `cname` line if you don't have a domain
  # Uncomment the `baseUrl` line if you don't have a custom domain and add your repo name there
  # cname: demo.upptime.js.org
  baseUrl: /cobi-upptime
  logoUrl: https://raw.githubusercontent.com/upptime/upptime.js.org/master/static/img/icon.svg
  name: "Cobi Upptime"
  introTitle: "**Upptime**"
  introMessage: Status
  navbar:
    - title: Status
      href: /
    - title: GitHub
      href: https://github.com/$OWNER/$REPO

# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
workflowSchedule:
  uptime: "*/10 * * * *"
